# Generated by Django 2.0.4 on 2018-05-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STEM', '0002_predecidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predecidos',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='STEM.Estudiante'),
        ),
    ]
