# Generated by Django 2.0.4 on 2018-05-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STEM', '0004_auto_20180520_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predecidos',
            name='estudiante',
        ),
    ]
