# Generated by Django 2.0.4 on 2018-05-29 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('STEM', '0007_auto_20180520_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
